# Generated by Django 4.1.3 on 2023-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputhour', models.IntegerField()),
                ('hourtomin', models.IntegerField()),
            ],
        ),
    ]
