# Generated by Django 4.1.3 on 2023-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_alter_dairy_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='color_type',
            field=models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('G', 'Green'), ('D', 'default')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='dairy',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
