# Generated by Django 4.1.3 on 2023-03-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_dairy_color_type_alter_dairy_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dairy',
            options={'ordering': ['color_type']},
        ),
    ]
